# Auditoría de seguridad — Playa Blanca (Vercel) — 21-jul-2026

Auditor multi-agente (35 agentes, 5 lentes + verificación adversarial). **30 hallazgos, 20 confirmados, 10 descartados (falsos positivos).**

Cada hallazgo fue verificado por un 2º agente escéptico. Solo se listan los confirmados como reales y explotables.

---

## [1] `CRITICA` — Clave maestra CRM_KEY/DASH_KEY hardcodeada en HTML público (3 ubicaciones servidas)

- **Archivo:** web-panama-LIVE/ceoapp1409.html:488 · web-panama-LIVE/crmdataplayablanca.html:450 · web-panama-LIVE/ceoapp1409.html (dentro del embed base64 B64_PANELJUAN, línea 911: decodificado contiene new URLSearchParams('embed=1&k=890D65CDA777439C932F'))
- **Público:** True
- **Evidencia:** const KEY="890D65CDA777439C932F";  (repetido idéntico en ceoapp1409.html:488 y crmdataplayablanca.html:450) + '...&k=890D65CDA777439C932F' horneado en el base64 B64_PANELJUAN de ceoapp1409.html
- **Riesgo:** Cualquiera que abra 'ver código fuente' de https://panama.playablancaresidences.com/ceoapp1409 o /crmdataplayablanca (ambas páginas públicas) lee la clave en texto plano. Esa clave es exactamente CRM_KEY/DASH_KEY que las APIs validan (api/panel.js:101-105, api/crm.js:91-94, api/leads.js:195-200, api/reporte.js:74-76 comparan req.query.key contra process.env.CRM_KEY||DASH_KEY). Con ella un atacante llama sin barrera a /api/panel, /api/crm, /api/leads y /api/reporte y exporta TODOS los leads con PII (nombre, teléfono, email), el gasto publicitario histórico y los informes del cliente. El 'gate' de clave es puramente cosmético: se compara en el cliente y la clave viaja en la URL. Decodificar el base64 del embed es trivial, así que 'esconderlo' ahí no protege nada.
- **Fix:** 1) ROTAR la clave ya: generar nuevas CRM_KEY, DASH_KEY, PANEL_KEY, RALPH_KEY, ARIE_KEY en Vercel env (la 890D65... queda quemada para siempre). 2) Dejar de comparar la clave en el navegador: mover la autenticación a un gate server-side (endpoint de login que setea cookie httpOnly de sesión) y que /api/panel|crm|leads|reporte exijan esa cookie, no ?key= en la URL. 3) Nunca hornear ninguna clave en HTML ni en base64; regenerar el embed B64_PANELJUAN sin la línea con k=. 4) Purgar la copia .bak (ver finding aparte) y limpiar el historial git donde quedó la clave.
- **Verificación:** CONFIRMADO real y crítico. La clave `890D65CDA777439C932F` está hardcodeada en `const KEY=` en dos HTML SERVIDOS públicamente: web-panama-LIVE/ceoapp1409.html:488 y web-panama-LIVE/crmdataplayablanca.html:450. Ninguno de los dos está en .vercelignore (allí solo está la variante .bak, paneljuan.html, agente.html, dashboard-leads.html), así que Vercel los sirve como HTML estático sin gate server-side. El cliente envía esa KEY como ?key= a endpoints reales: ceoapp1409 → /api/reporte, /api/leads, /api/crm (líneas 823/969/1095); crmdataplayablanca → /api/crm?all=1 y ?notes= (líneas 911/923). Esos endpoints validan req.query.key contra process.env.CRM_KEY||DASH_KEY (crm.js:91-94, leads.js:196-200, reporte.js:74-76, panel.js:101-106). Como los paneles públicos funcionan con esa clave, ES la CRM_KEY/DASH_KEY viva. También confirmado: el embed base64 B64_PANELJUAN (ceoapp1409.html:911) decodifica a `new URLSearchParams('embed=1&k=890D65CDA777439C932F')` → /api/panel; base64 no protege nada. Un atacante sin credenciales lee la clave con 'ver código fuente' y ejecuta /api/crm?key=...&all=1 para exfiltrar TODOS los leads con PII (nombre/teléfono/email), gasto e informes. Cumple ambos criterios de real=true. La copia .bak SÍ está cubierta por .vercelignore, así que esa NO es vía pública (solo relevante para higiene de git/rotación local). Matiz menor: el servidor SÍ compara la clave (hay auth real), no es 'solo en el cliente' como dice el finding, pero al ser el secreto público la auth queda anulada — no cambia la severidad. Severidad crítica correcta. Acción: rotar CRM_KEY/DASH_KEY ya (890D65... quemada), mover auth a cookie httpOnly server-side sin ?key= en URL, regenerar el embed sin la línea k=.

## [2] `CRITICA` — crmdataplayablanca.html (público) vuelca TODOS los leads con PII y CERO candado

- **Archivo:** web-panama-LIVE/crmdataplayablanca.html:450 (KEY) · :923 fetch · :1034 init
- **Público:** True
- **Evidencia:** line 450: const KEY="890D65CDA777439C932F"; · line 923: fetch(`${API}?key=${KEY}&all=1`) · line 1034 (INIT): fetchData(false); — no hay gate/prompt/overlay en todo el archivo (tail confirma init directo)
- **Riesgo:** Cualquiera que abra la URL pública (o vea el código fuente) recibe de inmediato el JSON de /api/crm?all=1 = nombre, teléfono, email, ciudad, asesor, presupuesto, plazo, comentarios y fecha de los ~2900 leads. No pide clave: la clave maestra está horneada y fetchData(false) corre solo al cargar. Además el 'ver código fuente' entrega la CRM_KEY/DASH_KEY en texto plano.
- **Fix:** Quitar la clave horneada del HTML. Implementar gate real bloqueante (patrón de crmceo.html: input password → /api/panel valida server-side → recién ahí renderiza) y guardar la clave sólo en sessionStorage tras login. Rotar CRM_KEY/DASH_KEY en Vercel env porque ya se filtró.
- **Verificación:** REAL y explotable. Verificado en disco: (1) crmdataplayablanca.html NO está en .vercelignore (que sí excluye dashboard-leads.html por PII, pero no este) -> se sirve en panama.playablancaresidences.com; la memoria del proyecto lo llama 'panel público de asesores'. (2) Línea 450 KEY='890D65CDA777439C932F' horneada en HTML público (ver-fuente la entrega). (3) SIN candado: grep de prompt/password/overlay/gate/login/clave solo halla localStorage de tema; el INIT (líneas 1031-1035) ejecuta fetchData(false) directo al cargar + refresco 30s. (4) Línea 923 fetch(`${API}?key=${KEY}&all=1`) -> /api/crm. (5) api/crm.js línea 94 valida key contra process.env.CRM_KEY||DASH_KEY (misma clave del finding #1) y con ?all=1 (MAXPAGES=30) el bloque de línea 151+ devuelve nombre/tel/email/ciudad/asesor/presupuesto/plazo/comentarios/fecha de ~2900 leads. AGRAVANTE no citado por el finder: SAMPLE_DATA (líneas 454-457) ya filtra 4 leads con PII real (nombre+tel+email) en el propio HTML servido, incluso sin llamar la API. Un atacante sin credenciales previas abre la URL y recibe el volcado + la clave maestra que también abre /api/panel, /api/leads, /api/reporte. Severidad crítica correcta; el finder NO exageró (si acaso es más grave que #1 porque aquí no hay gate alguno). Fix propuesto es adecuado: quitar clave del HTML, gate bloqueante server-side estilo crmceo.html, rotar CRM_KEY/DASH_KEY en Vercel env.

## [3] `CRITICA` — ceoapp1409.html (público) trae leads+gasto sin gate; clave maestra horneada

- **Archivo:** web-panama-LIVE/ceoapp1409.html:488 (KEY) · :1095 /api/crm · :969 /api/leads · :823 /api/reporte
- **Público:** True
- **Evidencia:** line 488: const KEY="890D65CDA777439C932F"; · line 1095: fetch('/api/crm?key='+KEY...) · line 969: fetch('/api/leads?key='+KEY...) · line 823: fetch('/api/reporte?key='+KEY...). grep de gate/overlay/type=password = 0 resultados de login (sólo scrim de drawer)
- **Riesgo:** Panel unificado del CEO servido públicamente en /ceoapp1409. Al abrirlo (o leyendo el fuente) se obtiene la clave maestra y con ella se carga automáticamente leads con PII, reporte de negocio y GASTO de campañas. Es el segundo lugar que publica la misma CRM_KEY/DASH_KEY.
- **Fix:** Igual que arriba: gate real validado en servidor antes de cargar data, sin clave incrustada. Rotar la clave. Considerar mover ceoapp1409.html a un slug no adivinable NO es suficiente por sí solo (la clave sigue expuesta); el arreglo de fondo es el gate + rotación.
- **Verificación:** CONFIRMADO real y explotable sin credenciales. (1) ceoapp1409.html SE SIRVE público: solo el .bak-20260715 está en .vercelignore, no el .html vivo; vercel.json tiene cleanUrls:true → reachable en https://panama.playablancaresidences.com/ceoapp1409; sin basic-auth de plataforma. (2) Línea 488: const KEY="890D65CDA777439C932F" en scope de script, legible con View Source; no hay ningún gate (grep de password/login/authGate = 0; el único overlay es el scrim del drawer y el único prompt() es para nombrar una categoría de link). (3) Línea 1109 tick();setInterval(tick,60000) dispara SOLO al abrir la página → fetch('/api/crm?key='+KEY). (4) El servidor valida esa misma clave contra process.env.CRM_KEY||DASH_KEY (crm.js:94, leads.js:200, reporte.js:76) con 401 si no coincide; como el panel funciona en prod, el valor horneado ES el secreto vivo. Ningún endpoint tiene restricción de origin/referer/CORS. (5) /api/leads devuelve PII completa (nombre, email, teléfono, presupuesto/objetivo_de_inversion, plazo, ciudad, asesor) de ~2900 leads, con export a Excel. Un atacante que abra /ceoapp1409 (o lea el fuente) saca la clave maestra y con ella exporta TODOS los leads con PII + gasto de campañas + reporte de negocio. Es el segundo HTML público que hornea la misma CRM_KEY/DASH_KEY. El finder NO exageró; si acaso subestimó el alcance (dump masivo de PII de miles de leads). Severidad crítica confirmada. Fix: gate real validado en servidor + rotar la clave; cambiar de slug NO basta porque la clave sigue en el fuente.

## [4] `CRITICA` — Clave maestra 890D65... = CRM_KEY/DASH_KEY abre TODOS los endpoints /api por curl

- **Archivo:** expuesta en crmdataplayablanca.html:450 y ceoapp1409.html:488
- **Público:** True
- **Evidencia:** Los endpoints validan bien server-side (crm.js:94, leads.js:200, reporte.js:76, panel.js:105-107 → okKeys incluye CRM_KEY/DASH_KEY, meta-events.js:68). El problema es que el valor válido está publicado en HTML público, así que el 401 no protege nada.
- **Riesgo:** Con la clave visible en el fuente, un atacante NO necesita abrir ninguna página: hace curl directo a /api/crm?key=..&all=1 (dump total de leads PII), /api/leads?key=.. (Excel/CSV de compradores con presupuesto), /api/reporte?key=.. (gasto y métricas), /api/panel?key=.. y /api/meta-events?key=.. (gasto/pixel). Un solo secreto compromete todo el CRM y la data de Meta.
- **Fix:** Rotar YA el valor de CRM_KEY/DASH_KEY en Vercel env. Sacar la clave de todo HTML servido. Emitir claves distintas por rol/persona en vez de una maestra compartida, y validar por sesión (cookie httpOnly) en lugar de key en querystring (que además queda en logs/historial).
- **Verificación:** CONFIRMADO como exposición real y explotable sin credenciales previas. (1) La clave 890D65CDA777439C932F está hardcodeada en web-panama-LIVE/crmdataplayablanca.html:450 y ceoapp1409.html:488, y AMBOS archivos se sirven públicos: verificado en vivo HTTP 200 en panama.playablancaresidences.com/ceoapp1409 y /crmdataplayablanca, con la clave presente en los bytes entregados. No están en .vercelignore (solo el .bak lo está). (2) Los 5 endpoints validan esa clave server-side contra CRM_KEY/DASH_KEY: crm.js:94, leads.js:200, reporte.js:76, panel.js:105-107 (okKeys), meta-events.js:68-69 — líneas citadas por el finder son exactas. (3) Es la clave VIVA: el propio JS de la página hace fetch('/api/crm?key=890D65...&all=1') (crmdataplayablanca.html:923) y el panel funciona 200, por lo que el valor necesariamente == process.env.CRM_KEY. Un atacante hace curl directo sin abrir ninguna página → dump total de leads PII (/api/crm?all=1), Excel/CSV de compradores con presupuesto (/api/leads), gasto/métricas (/api/reporte, /api/panel, /api/meta-events). No exageró la severidad; si acaso la subestima: key= en querystring además queda en logs/proxy/historial. Nota: la clave también está en ceoapp1409.bak-20260715.html:380 pero ese .bak SÍ está en .vercelignore = no servido (fuera de alcance, correcto). El valor no aparece en .env de raíz (vive solo en Vercel env), pero la evidencia funcional es concluyente. Fix: rotar CRM_KEY/DASH_KEY en Vercel YA, sacar la clave de todo HTML servido, claves por rol y validación por sesión (cookie httpOnly) en vez de key en querystring.

## [5] `CRITICA` — Clave maestra en HTML PÚBLICO abre TODOS los endpoints de datos (crm/leads/panel/reporte/meta-events) — expuesta en 2 archivos, no 1

- **Archivo:** web-panama-LIVE/crmdataplayablanca.html:450 (y web-panama-LIVE/ceoapp1409.html)
- **Público:** True
- **Evidencia:** crmdataplayablanca.html:450 `const KEY="890D65CDA777439C932F";` → fetch a /api/crm. crm.js:94 / leads.js:200 / panel.js:107 / reporte.js:76 / meta-events.js:69 validan `req.query.key` contra CRM_KEY/DASH_KEY = ese mismo valor.
- **Riesgo:** Cualquiera que abra el HTML (Ver código fuente) obtiene la clave y la usa contra los 5 endpoints protegidos. La 'auth' de servidor SÍ existe pero es inútil porque el secreto es público. Verificado alcance: la clave NO está solo en ceoapp1409.html (hallazgo #1 ya conocido) sino TAMBIÉN en crmdataplayablanca.html (panel de asesores, servido públicamente, NO está en .vercelignore).
- **Fix:** Rotar CRM_KEY/DASH_KEY YA. Sacar la clave de todo HTML: autenticar por sesión/cookie httpOnly server-side (login real) en vez de una clave horneada en el cliente. Mientras tanto, mover crmdataplayablanca.html y ceoapp1409.html detrás de auth o a .vercelignore.
- **Verificación:** CONFIRMADO. crmdataplayablanca.html:450 tiene `const KEY="890D65CDA777439C932F"` y el archivo NO está en .vercelignore -> se sirve público. Verificado en vivo: https://panama.playablancaresidences.com/crmdataplayablanca devuelve 200 (título "Panel de Leads · Playa Blanca Residences") y la clave aparece en el HTML entregado. El panel hace fetch a /api/crm?key=${KEY}&all=1 (línea 923) y &notes= (911). Los 5 endpoints validan SOLO por clave: crm.js:94, leads.js:200, panel.js:105-106, reporte.js:76, meta-events.js:68-69, todos comparan req.query.key contra process.env.CRM_KEY||DASH_KEY (panel/meta también aceptan PANEL/RALPH/ARIE_KEY). Prueba de que el valor horneado == la env del servidor: el panel sirve leads reales en producción; si no coincidiera daría 401 siempre y estaría vacío -> coinciden (el valor no está en el .env local, las env viven en Vercel, consistente). La ampliación del finder es correcta: la clave está en DOS archivos públicos (crmdataplayablanca.html Y ceoapp1409.html); un tercero, ceoapp1409.bak-20260715.html, también la tiene pero SÍ está en .vercelignore (riesgo bajo). Impacto: atacante anónimo (ver código fuente) saca la clave y llama a crm/leads/panel/reporte/meta-events -> PII completa de miles de leads (nombres, teléfonos, emails, presupuesto) + inyección de eventos CAPI. Cumple ambos criterios (servido público + alcanzable sin credenciales previas). Severidad critica correcta, no exagerada. Fix: rotar CRM_KEY/DASH_KEY YA, sacar la clave de TODO HTML, auth por sesión/cookie httpOnly server-side; mientras tanto poner crmdataplayablanca.html y ceoapp1409.html tras auth o en .vercelignore.

## [6] `CRITICA` — Exfiltración masiva de PII (~2900 leads: nombre, teléfono, email, presupuesto) vía crm.js?all y leads.js?audiencia con la clave filtrada

- **Archivo:** web-panama-LIVE/api/leads.js:136-189 (audiencia) y web-panama-LIVE/api/crm.js:151-181 (?all)
- **Público:** True
- **Evidencia:** leads.js: GET /api/leads?key=...&audiencia=1&format=xlsx|csv → metaCsv/xsheet vuelcan email,phone,fn,ln,ciudad de todos los compradores. crm.js ?all devuelve tel/email/nombre por lead; ?notes=<id> devuelve el cuerpo de notas privadas.
- **Riesgo:** Consecuencia concreta del finding #1: con la clave pública se descarga toda la base de datos de compradores (PII sensible + presupuesto declarado) en Excel/CSV listos para reventa/retargeting no autorizado, y las notas internas de gestión. Exposición de datos personales (riesgo legal/privacidad).
- **Fix:** Rotar clave y mover a auth de sesión real. Registrar/limitar exportaciones. Minimizar datos: no exponer teléfono/email completos en respuestas de panel salvo tras auth fuerte.
- **Verificación:** CONFIRMADO y explotable sin credenciales previas. Cadena verificada leyendo los archivos: (1) web-panama-LIVE/api/crm.js y api/leads.js NO están en .vercelignore (solo lista HTML/docs/backups + node_modules), por lo que Vercel los sirve como /api/crm y /api/leads; vercel.json solo reescribe /gracias y /privacidad y no protege /api. (2) El ÚNICO gate de ambos es ?key= comparado contra CRM_KEY/DASH_KEY (crm.js:91-94; leads.js:196-200). (3) La clave 890D65CDA777439C932F está hardcodeada en ceoapp1409.html:488 (const KEY=...), archivo PÚBLICO (solo el .bak está en .vercelignore), y se usa como ?key=+KEY contra /api/crm, /api/leads y /api/reporte (líneas 823/969/1095) — lo que prueba que KEY === env CRM_KEY/DASH_KEY. Con esa clave copiada del HTML público, un atacante anónimo obtiene: /api/crm?all=1 → todos los leads de formulario con nombre/tel/email/ciudad/asesor/presupuesto/plazo/comentarios (crm.js:151-181); /api/crm?notes=<id> → cuerpo de notas privadas de gestión de cualquier contacto (crm.js:97-121); /api/leads?audiencia=1&format=xlsx → Excel con Nombre/Email/Teléfono/Ciudad/Presupuesto (xsheet 94-130); &format=csv → CSV email,phone,fn,ln,country,ct listo para Meta (metaCsv 131-134). Corrección de severidad: el finder puso 'alta' pero esto es una brecha de la base COMPLETA de compradores (~2900 PII: nombre+tel+email+presupuesto declarado) MÁS notas internas, exfiltrable en bulk y en formatos listos para reventa/retargeting, por un atacante anónimo sin credenciales → severidad CRÍTICA. Nota: comparte causa raíz con el hallazgo crítico #1 (clave maestra filtrada en ceoapp1409.html); esta es su consecuencia concreta de exfiltración de datos. Remediación conjunta: rotar la clave, sacarla del HTML público y sustituir por auth de sesión real; además minimizar campos y registrar/limitar exportaciones.

## [7] `CRITICA` — Clave maestra pública abre TODOS los endpoints de PII (dump completo de leads Panamá + Colombia)

- **Archivo:** web-panama-LIVE/ceoapp1409.html:488 y web-panama-LIVE/crmdataplayablanca.html:450
- **Público:** True
- **Evidencia:** const KEY="890D65CDA777439C932F"; horneada en dos HTML servidos públicamente. Es la misma CRM_KEY/DASH_KEY que exigen crm.js:94, leads.js:200, panel.js:105, reporte.js:76 y landing-colombia-full/api/leads.js:27.
- **Riesgo:** Cualquiera que abra el fuente saca la clave y llama sin más: /api/crm?key=...&all=1 (vuelca ~2900 contactos: nombre, email, teléfono, presupuesto, ciudad, asesor, estado, nº notas), /api/leads?key=...&audiencia=1&format=xlsx|csv (descarga Excel/CSV de compradores con nombre+email+teléfono+presupuesto+notas), /api/crm?key=...&notes=<id> (notas libres del asesor por contacto) y /api/panel, /api/reporte. La MISMA clave abre landing-colombia-full.vercel.app/api/leads?key=... (leads de la landing Colombia). Fuga masiva de datos personales.
- **Fix:** Rotar CRM_KEY/DASH_KEY en Vercel env de AMBOS proyectos. Sacar la clave del HTML: no hornear credenciales en el cliente; mover a un gate server-side (login que setea cookie httpOnly de sesión) y que las páginas no conozcan la clave del API. Usar claves distintas por proyecto para acotar el radio.
- **Verificación:** CONFIRMADO. La clave 890D65CDA777439C932F esta horneada en dos HTML servidos publicamente: web-panama-LIVE/ceoapp1409.html:488 y crmdataplayablanca.html:450. Ninguno esta en .vercelignore (solo el .bak lo esta), asi que ambos llegan al navegador. Es exactamente la clave que las paginas pasan como ?key= a los endpoints: ceoapp1409 llama /api/crm, /api/leads y /api/reporte con KEY; crmdataplayablanca:923 llama /api/crm?key=${KEY}&all=1 y :911 &notes=. Los gates lo exigen contra env: crm.js:94 (CRM_KEY||DASH_KEY), leads.js:200 (DASH_KEY||CRM_KEY), reporte.js:76 (CRM_KEY), panel.js:105. Como los paneles funcionan en produccion, la KEY servida = CRM_KEY de Vercel; si no, todo daria 401. Un atacante sin credenciales lee el fuente, saca la clave y vuelca ~2900 contactos con nombre/email/tel/presupuesto/ciudad/asesor/estado (crm.js:151-164 con all=1, hasta 30 paginas), descarga Excel/CSV de compradores (leads.js audiencia=1 format=xlsx|csv, attachment) y lee notas libres del asesor (notes=<id>). Fuga masiva de PII. UNICO matiz: la afirmacion de que la MISMA clave abre landing-colombia-full/api/leads.js:27 depende de que el DASH_KEY del proyecto Colombia tenga identico valor; ese env no esta en el repo (el .env raiz no tiene CRM_KEY/DASH_KEY, solo GEMINI/HS_CONTROL) y no es verificable desde el codigo, es plausible pero no probado. No reduce la severidad: la exposicion de Panama por si sola es critica, y crmdataplayablanca.html es una fuga completa e independiente (HTML publico + clave en claro + dump all=1 directo). Fix del finder correcto: rotar CRM_KEY/DASH_KEY en Vercel de ambos proyectos, sacar la clave del cliente (gate server-side con cookie httpOnly), y usar claves distintas por proyecto.

## [8] `CRITICA` — Panel de asesores público y SIN gate que auto-vuelca todo el CRM en el navegador al abrirlo

- **Archivo:** web-panama-LIVE/crmdataplayablanca.html:920-935 (fetchData) — NO está listado en web-panama-LIVE/.vercelignore
- **Público:** True
- **Evidencia:** En boot: fetch(`/api/crm?key=${KEY}&all=1`) y applyData(j.leads) renderiza la lista completa de leads. No hay gate/login (a diferencia de crmceo.html que sí pide clave en /api/panel). El .vercelignore de Panamá NO incluye crmdataplayablanca.html, así que la ruta es pública.
- **Riesgo:** Abrir panama.playablancaresidences.com/crmdataplayablanca.html muestra a cualquier visitante el data-grid con la PII de todos los leads, sin saber nada de la API ni de la clave: explotación de cero esfuerzo de la clave expuesta. Es la vía de entrega más grave del finding #1.
- **Fix:** Despublicar la página: añadir crmdataplayablanca.html al .vercelignore (como ya se hizo con dashboard-leads.html/paneljuan.html), o convertirla en un panel con auth server-side real. El panel de leads no debe ser una ruta pública estática.
- **Verificación:** CONFIRMADO en disco Y en producción viva. (1) Público: crmdataplayablanca.html NO está en web-panama-LIVE/.vercelignore (que sí despublica dashboard-leads/paneljuan/agente); la ruta https://panama.playablancaresidences.com/crmdataplayablanca responde 200 (un 308 previo solo quita el .html por clean-URLs de Vercel). (2) Sin gate: no hay prompt/clave/login; el boot llama fetchData(false) en línea 1034 + auto-refresh setInterval en 1035. (3) Clave maestra horneada en el HTML SERVIDO: línea 450 const KEY="890D65CDA777439C932F" (verificado con grep -c=1 sobre el curl del HTML en vivo). (4) fetchData (920-935): fetch('/api/crm?key=${KEY}&all=1') -> applyData(j.leads) pinta el grid completo. (5) api/crm.js:94 valida key===CRM_KEY/DASH_KEY y :151 con ?all=1 devuelve TODOS los leads con PII. Explotación probada sin credenciales: curl en vivo del endpoint con esa clave devolvió total:2910 leads reales con nombre, tel +507, email, país y presupuesto declarado. Un simple visitante que abre la URL recibe volcados automáticamente los 2910 leads en su navegador, sin saber nada de la API ni de la clave. Es el vector de entrega de cero esfuerzo del hallazgo crítico #1 (clave expuesta). Ajuste de severidad: SUBO de 'alta' a 'critica' — es un volcado masivo de PII (incl. datos financieros de inversión) de 2910 personas reales, alcanzable con solo navegar a la ruta, sin interacción ni conocimiento previo. El finder NO exageró; si acaso se quedó corto. Fix correcto: despublicar la página (añadirla al .vercelignore) o convertirla en panel con auth server-side real, y ADEMÁS rotar la CRM_KEY/DASH_KEY (que también abre /api/panel, /api/leads, /api/reporte) porque ya quedó expuesta en el HTML público.

## [9] `CRITICA` — Clave maestra 890D65 hardcodeada en un SEGUNDO panel público (crmdataplayablanca.html), además de ceoapp1409.html

- **Archivo:** web-panama-LIVE/crmdataplayablanca.html:450 (y ceoapp1409.html:488 + blob B64_PANELJUAN)
- **Público:** True
- **Evidencia:** const KEY="890D65CDA777439C932F";  — mismo valor CRM_KEY/DASH_KEY que abre /api/crm, /api/leads, /api/panel, /api/reporte, /api/meta-events, /api/vigia
- **Riesgo:** El hallazgo #1 (clave en ceoapp1409.html) tiene MAYOR alcance del anotado: la misma clave maestra está en TRES ubicaciones servidas públicamente — ceoapp1409.html línea 488, el blob base64 B64_PANELJUAN embebido dentro de ese mismo archivo, y crmdataplayablanca.html línea 450 (este NO está en .vercelignore, se sirve entero). Cualquiera que abra el código fuente de crmdataplayablanca.html saca la clave y con ella lee todos los leads (PII: nombre/tel/email/presupuesto), el gasto y los reportes vía API. Rotar la clave solo en ceoapp1409 NO cierra el hueco: hay que rotarla en los 3 sitios y en Vercel env.
- **Fix:** Eliminar la clave del HTML en AMBOS paneles y del blob embebido. Mover la autenticación al servidor (login real con cookie httpOnly/SameSite o gate server-side), rotar CRM_KEY/DASH_KEY en Vercel env, y no volver a hornear claves en archivos servidos. Verificar con: grep -rn 890D65 sobre todos los .html no ignorados.
- **Verificación:** CONFIRMADO real y explotable por atacante anónimo. (1) crmdataplayablanca.html:450 tiene `const KEY="890D65CDA777439C932F"` y NO está en .vercelignore (verifiqué el .vercelignore completo: lista dashboard-leads.html/MASTER/backups pero NO crmdataplayablanca.html) -> se sirve entero al navegador. (2) El propio panel hace fetch('/api/crm?key=890D65...&all=1') (líneas 911/923); crm.js:94 valida req.query.key===process.env.CRM_KEY||DASH_KEY (401 sin clave, dump de leads con PII con ella). El panel está vivo en prod, luego el valor horneado ES el CRM_KEY real. Misma clave abre /api/leads (leads.js:200), /api/reporte (74), /api/panel (105), /api/vigia (69), /api/meta-events (68). (3) Verifiqué la 3a ubicación: decodifiqué el blob B64_PANELJUAN (ceoapp1409.html:911, 53KB) y el texto decodificado SÍ contiene el literal 890D65 (usa _P -> /api/panel). Los 3 puntos citados existen. Severidad se mantiene critica: el finder NO exageró; crmdataplayablanca.html es un archivo público independiente, así que arreglar solo ceoapp1409 deja el hueco abierto. Fix: rotar CRM_KEY/DASH_KEY en Vercel env + eliminar la clave de los 3 sitios servidos + auth server-side (cookie httpOnly).

## [10] `CRITICA` — PANEL_KEY (clave del cron 'ralph-ceo-pb-7q29') es recuperable del ceoapp1409.html público → abre /api/wa-grupo para spamear el grupo de WhatsApp

- **Archivo:** web-panama-LIVE/ceoapp1409.html (blob B64_AGENTE, línea ~912) · vercel.json crons · api/wa-grupo.js:23 · api/hs-webhook.js:177
- **Público:** True
- **Evidencia:** Decodificando const B64_AGENTE="..." (base64 embebido, público) aparece: 'ralph-ceo-pb-7q29'. Es el mismo PANEL_KEY que gatea wa-grupo.js:23 y hs-webhook.js:177, y el que va en el cron /api/wa-grupo?key=ralph-ceo-pb-7q29&auto=1 de vercel.json.
- **Riesgo:** Exactamente el caso 'clave de cron que también aparece en HTML público'. La clave del cron está en vercel.json (no servido) PERO su VALOR se recupera decodificando el blob base64 del agente embebido en ceoapp1409.html (sí servido). Con esa clave un atacante hace POST /api/wa-grupo?key=ralph-ceo-pb-7q29 con {text:'...'} y ENVÍA MENSAJES ARBITRARIOS al grupo de WhatsApp de los asesores (phishing/spam a personas reales del cliente), y puede disparar el envío de reportes con Excel de leads (PII) al grupo. La misma clave también satisface el gate externo de /api/hs-webhook, /api/vigia y /api/wa-lead-poll.
- **Fix:** Separar PANEL_KEY de la clave del cron: usar el mecanismo de Vercel Cron con CRON_SECRET (header Authorization: Bearer) en vez de ?key= en la URL; NO embeber agente.html (con la clave) en un archivo público; rotar PANEL_KEY. Para wa-grupo, exigir además una clave dedicada distinta de la de paneles (como ya hace hsapi con HS_CONTROL_KEY).
- **Verificación:** REAL y bien calificado (critica). Cadena verificada extremo a extremo: (1) ceoapp1409.html es PUBLICO (no esta en .vercelignore; solo el .bak). Linea 912 embebe const B64_AGENTE=\"...\"; al decodificar el base64 aparece literalmente: let KEY=...get('k')||'ralph-ceo-pb-7q29'. (2) Ese valor ES el PANEL_KEY vivo: vercel.json:18 corre el cron /api/wa-grupo?key=ralph-ceo-pb-7q29&auto=1, y el gate de wa-grupo.js:23 es process.env.PANEL_KEY||CRM_KEY||DASH_KEY; para que ese cron diario funcione (esta activo segun el proyecto) PANEL_KEY=ralph-ceo-pb-7q29, y es DISTINTO del 890D65 (CRM_KEY del hallazgo #1). (3) La clave habilita ENVIO, no solo lectura: wa-grupo.js tiene rama de texto libre (POST {text:'...'} -> sendMessage message:String(req.body.text)) = mensajes ARBITRARIOS al grupo real de WhatsApp de Ralph+asesores (phishing/impersonacion), y ?auto=1/?tipo=dia genera+envia Excel de leads con PII. hs-webhook.js:177, vigia y wa-lead-poll comparten el mismo gate. Gate = comparacion string plana sin auth previa, alcanzable por cualquiera. EL FINDER SE QUEDO CORTO: chatId=q.to||group permite &to=<numero> para redirigir el Excel de leads (PII) a un destino WhatsApp arbitrario del atacante = exfiltracion, no solo spam al grupo. Es un critico INDEPENDIENTE del 890D65 (clave distinta + capacidad distinta: inyeccion de mensajes + exfil PII). Fix del finder correcto (CRON_SECRET/Bearer, no embeber agente en HTML publico, rotar PANEL_KEY, clave dedicada para wa-grupo).

## [11] `ALTA` — /api/wa-lead-poll?archive=<email> BORRA (DELETE) cualquier contacto de HubSpot — escritura destructiva alcanzable con la clave filtrada

- **Archivo:** web-panama-LIVE/api/wa-lead-poll.js:59-67
- **Público:** True
- **Evidencia:** if(q.archive && c.id){ await hs("/crm/v3/objects/contacts/"+c.id,{method:"DELETE"},token); } — auth solo `key === PANEL_KEY||CRM_KEY||DASH_KEY` (línea 19-20), que es la clave pública.
- **Riesgo:** Con la clave maestra filtrada, un atacante hace GET /api/wa-lead-poll?key=890D65...&archive=cualquier@email.com y elimina leads reales del CRM uno por uno. Mismo endpoint permite ?setup (crear props) y ?fixtipo (PATCH de propiedad). Borrado = pérdida de datos del cliente.
- **Fix:** Rotar clave (finding #1). Exigir una clave dedicada (tipo HS_CONTROL_KEY) para operaciones de escritura/borrado, separada de la clave de lectura de paneles. Idealmente quitar la capacidad DELETE del endpoint público.
- **Verificación:** REAL, pero el finder erró la clave. El endpoint /api/wa-lead-poll ES público (api/ no está en .vercelignore) y en la línea 65 hace DELETE real de un contacto HubSpot vía GET ?archive=<email> (sin guard de método). CORRECCIÓN CLAVE: la auth (línea 19) es `PANEL_KEY || CRM_KEY || DASH_KEY` y toma la PRIMERA definida. PANEL_KEY SÍ está seteada = 'ralph-ceo-pb-7q29' (lo prueba el cron vercel.json:18 wa-grupo?key=ralph-ceo-pb-7q29 con la misma cadena de fallback). Por tanto la clave aceptada es ralph-ceo-pb-7q29, NO el master 890D65 del finding #1 — un atacante con solo 890D65 recibe 401 aquí, así que el exploit tal como lo describe el finder (key=890D65&archive=) FALLA. SIN EMBARGO la vuln se sostiene por otra vía: ceoapp1409.html (público, NO excluido) embebe un blob base64 (el embed de agente.html) que al decodificar contiene en texto plano `KEY = ... || 'ralph-ceo-pb-7q29'`. O sea PANEL_KEY es recuperable por cualquiera: fetch /ceoapp1409 → atob del blob → obtiene ralph-ceo-pb-7q29 → GET /api/wa-lead-poll?key=ralph-ceo-pb-7q29&archive=victima@mail.com. Los emails a atacar se enumeran con /api/crm (ese sí toma 890D65). La misma clave habilita ?setup (crear props) y ?fixtipo (PATCH schema) y el PATCH wa_alerta = manipulación del pipeline. MATIZ DE SEVERIDAD: el DELETE de HubSpot = ARCHIVAR (papelera, recuperable ~90 días), no borrado duro — el propio comentario dice 'archiva (borra)'; además es de a un email por vez (search email EQ). Por eso es escritura destructiva reversible, no destrucción permanente: se mantiene ALTA, no crítica. Fix: rotar 890D65 Y ralph-ceo-pb-7q29, dejar de embeber claves en HTML público, exigir clave dedicada de escritura (tipo HS_CONTROL_KEY) distinta de la de paneles, y quitar/gate la capacidad DELETE del endpoint público.

## [12] `ALTA` — /api/wa-grupo con POST {text} envía un mensaje ARBITRARIO al grupo de WhatsApp de asesores — con la clave filtrada

- **Archivo:** web-panama-LIVE/api/wa-grupo.js:42-46
- **Público:** True
- **Evidencia:** if(req.method==="POST" && req.body && req.body.text){ ... sendMessage ... message:String(req.body.text) } — auth solo `key === PANEL_KEY||CRM_KEY||DASH_KEY` (línea 23-24).
- **Riesgo:** Con la clave pública (o PANEL_KEY 'ralph-ceo-pb-7q29'), un atacante manda cualquier texto al grupo real de WhatsApp del cliente: phishing/suplantación a los asesores (ej. 'nuevo protocolo, escriban a este número'), spam, o disparo de reportes con PII (Excel de leads) a un destino ?to= controlado.
- **Fix:** Rotar claves. Separar la capacidad de 'texto libre al grupo' detrás de una clave dedicada de escritura y/o allowlist de remitentes. No reutilizar la misma clave de lectura para acciones que envían mensajes.
- **Verificación:** REAL y explotable. /api/wa-grupo.js está en web-panama-LIVE/api/ (NO en .vercelignore) → función servida públicamente; hasta figura como cron en vercel.json. Líneas 42-46: POST con body JSON {text:"..."} envía message:String(req.body.text) al chatId (por defecto GREENAPI_GROUP, el grupo real de asesores). Corrección al finder: la auth (líneas 23-24) resuelve panelKey = PANEL_KEY || CRM_KEY || DASH_KEY; como PANEL_KEY SÍ está seteada en prod (el cron de vercel.json llama key=ralph-ceo-pb-7q29 y debe funcionar), el || corta en PANEL_KEY. Por tanto la clave maestra 890D65 (CRM/DASH) NO autentica este endpoint — la clave válida es 'ralph-ceo-pb-7q29'. PERO esa clave también está filtrada públicamente: decodifiqué el blob base64 B64_AGENTE embebido en ceoapp1409.html (público) y contiene literalmente KEY='ralph-ceo-pb-7q29' (y B64_PANELJUAN filtra 890D65...). Cualquiera baja ceoapp1409.html, decodifica una constante y obtiene la clave sin credenciales previas. Con ella un atacante puede: (a) POST {text} → texto arbitrario al grupo real de WhatsApp del cliente (phishing/suplantación de la agencia); (b) ?to=<numero>@c.us → enviar desde el WhatsApp del cliente a destinos arbitrarios; (c) GET ?tipo=dia&to=<atacante> → exfiltrar el Excel de leads (PII) a un número controlado. Se cumplen ambos criterios: endpoint servido + secreto/acción alcanzable sin credenciales. Severidad 'alta' correcta (capacidad activa de envío + exfil PII sobre el leak de claves #1). Fix real: la raíz es rotar claves y dejar de embeber los blobs con claves horneadas en ceoapp1409.html; además separar la acción de envío detrás de clave dedicada y allowlist de 'to'/remitentes, no reutilizar clave de lectura.

## [13] `ALTA` — Bypass de autenticación por User-Agent 'vercel-cron' en /api/vigia y /api/parte (spoofable) → escrituras en HubSpot + spam sin ninguna clave

- **Archivo:** web-panama-LIVE/api/vigia.js:64-70 y web-panama-LIVE/api/parte.js:16-19
- **Público:** True
- **Evidencia:** vigia.js: `const isCron = ua.includes("vercel-cron"); if(!isCron && !okKey){...401}`. parte.js igual: `if (!isCron && key !== CRM_KEY){...401}`. El User-Agent lo controla el cliente.
- **Riesgo:** Cualquiera manda `User-Agent: vercel-cron` y pasa como cron SIN clave. En vigia eso habilita: ?setup (crear propiedad en HubSpot), PATCH masivo de contactos (estampar vigia_alerta) y envío de mensajes de Telegram a Juan. En parte, dispara generación con Gemini + Telegram (abuso de cuota/spam). No requiere conocer ningún secreto.
- **Fix:** No confiar en el User-Agent como autenticación. Vercel Cron soporta un secreto (CRON_SECRET / header Authorization) — validar ese header en su lugar. Para /api/vigia y /api/parte exigir clave real siempre y verificar el secreto de cron por cabecera firmada.
- **Verificación:** CONFIRMADO real y explotable sin credenciales. Verificado en disco: web-panama-LIVE/api/vigia.js:64-70 usa `isCron = ua.includes("vercel-cron")` y el gate es `if(!isCron && !okKey) 401`; web-panama-LIVE/api/parte.js:16-19 idéntico con `key !== CRM_KEY`. El header User-Agent lo controla el cliente (curl -A vercel-cron), así que el atacante pasa como cron SIN clave. Ambos endpoints son PÚBLICOS: no aparecen en .vercelignore (que solo lista HTML/docs concretos) → servidos en panama.playablancaresidences.com/api/vigia y /api/parte. vercel.json confirma que el cron real NO manda key ni valida CRON_SECRET/Authorization; la autenticación de cron depende ÚNICAMENTE del User-Agent spoofable (no hay verificación de secreto firmado). Producción sin deployment protection. Impacto sin secreto: (1) vigia?setup=1 crea propiedad en HubSpot; (2) flujo default hace PATCH a contactos (estampa vigia_alerta) + Telegram a Juan; (3) parte dispara Gemini + hasta 6 mensajes Telegram por hit = abuso de cuota/spam. DOS agravantes que el finder no mencionó: (a) vigia?seed=1&window=10080 marca hasta 100 leads como 'ya avisados' SIN enviar → SUPRIME alertas legítimas de leads calientes (denegación de aviso, daño de negocio); (b) vigia?dry=1&window=10080 devuelve en el JSON de respuesta hasta 100 NOMBRES de leads + tier de presupuesto + campaña = lectura de PII no autenticada. Severidad se mantiene en 'alta' (no crítica: no expone teléfonos/emails completos ni permite mover fondos ni tomar cuentas, pero es bypass de auth sin credenciales con escrituras a CRM + supresión de alertas + fuga de nombres). Fix correcto: validar CRON_SECRET/Authorization firmado en vez de confiar en el User-Agent, y exigir clave real siempre en accesos manuales.

## [14] `ALTA` — Bypass de autenticación en crons por User-Agent falsificable (parte.js y vigia.js)

- **Archivo:** web-panama-LIVE/api/parte.js:16-19 · web-panama-LIVE/api/vigia.js:64-70
- **Público:** True
- **Evidencia:** const isCron = ua.includes("vercel-cron"); ... if(!isCron && key!==CRM_KEY){401}  — el User-Agent lo controla 100% el cliente.
- **Riesgo:** La autorización de estos endpoints depende SOLO de que el header User-Agent contenga 'vercel-cron', que cualquier atacante externo puede enviar (curl -H 'User-Agent: vercel-cron'). Sin clave, un tercero dispara: parte.js → llamadas a Gemini (drena la cuota gratuita) + mensajes de Telegram al chat del Jefe (spam); vigia.js → el polling del vigía y potencial envío de WhatsApp al grupo. Es un bypass real de la clave.
- **Fix:** No confiar en User-Agent. Usar el patrón oficial de Vercel: variable CRON_SECRET y verificar el header Authorization: Bearer ${CRON_SECRET} (Vercel lo inyecta en los cron). Rechazar (401) cualquier request sin ese bearer. Mantener la clave manual como segundo camino, pero eliminar el atajo por User-Agent.
- **Verificación:** CONFIRMADO. parte.js:16-19 y vigia.js:64-70 usan `isCron = ua.includes("vercel-cron")` para saltarse el chequeo de CRM_KEY. El header User-Agent lo controla 100% el cliente y Vercel NO lo filtra ni valida en requests entrantes, así que `curl -H "User-Agent: vercel-cron"` pone isCron=true y salta la clave. Ambos endpoints son públicos: NO están en .vercelignore y están registrados como crons en vercel.json; probé en vivo (UA normal, sin key) y devuelven HTTP 401 {"error":"no autorizado"} = desplegados y alcanzables sin credencial. Impacto real sin credenciales: parte.js → spam Telegram al Jefe (hasta 6 msgs/llamada, en bucle) + drena la cuota gratis de Gemini; vigia.js → escribe en HubSpot (stampAlerta PATCH), spam Telegram, y DOS vectores extra que el finder no vio y agravan: ?dry=1&window=10080 devuelve NOMBRES/tier/campaña de leads recientes en el JSON de respuesta (fuga de PII sin auth), y ?seed=1&window=10080 marca todos los leads recientes como ya-avisados SIN enviar → suprime silenciosamente las alertas reales de comprador caliente (golpea el KPI del cliente). Correcciones al finder: vigia.js manda TELEGRAM, no WhatsApp (el WhatsApp vive en wa-lead-poll.js/wa-grupo.js); y estos endpoints NO filtran CRM_KEY en sí. El bypass central es totalmente válido; si acaso el impacto es algo mayor que lo descrito. Severidad 'alta' correcta: sin autenticación, explotación trivial (un curl con un header), con consecuencias de integridad (escrituras HubSpot, supresión de alertas) y fuga de PII en producción viva ligada al flujo de leads. No es 'critica' porque por esta vía sola no hay volcado masivo del CRM ni toma de cuenta. Fix propuesto (CRON_SECRET + Authorization: Bearer, patrón oficial de Vercel, y eliminar el atajo por User-Agent) es correcto.

## [15] `MEDIA` — /api/conversion (Panamá y Colombia) SIN autenticación: crea/upsertea contactos en HubSpot e inyecta eventos arbitrarios al Pixel de Meta

- **Archivo:** web-panama-LIVE/api/conversion.js:17-97 y landing-colombia-full/api/conversion.js:23-97
- **Público:** True
- **Evidencia:** No hay chequeo de clave. `batch/upsert` con `idProperty:'email'` (conversion.js:74-77) CREA el contacto si no existe. ALLOWED_EVENTS incluye 'Purchase' y 'Lead' (línea 29).
- **Riesgo:** El CORS (Access-Control-Allow-Origin al dominio) NO protege: sólo limita lectura desde el navegador, no un POST con curl. Un atacante hace POST masivos: (1) crea/contamina contactos en HubSpot poniendo email arbitrario + fb_fbc/fbp/event_id; (2) inyecta eventos falsos (Lead/Purchase) al Pixel 2195.../1923..., corrompiendo la optimización de las campañas y el reporte. Sin rate limit = envenenamiento masivo.
- **Fix:** Añadir un secreto compartido/firma (HMAC del payload) o al menos verificar Origin/Referer server-side y rechazar sin él. Validar que el email pertenezca a un flujo legítimo antes del upsert. Añadir rate limiting por IP.
- **Verificación:** CONFIRMADO explotable pero severidad ajustada de 'alta' a 'media'. Verificado leyendo ambos archivos: web-panama-LIVE/api/conversion.js y landing-colombia-full/api/conversion.js. (1) PÚBLICOS: ninguno está en .vercelignore (Panamá ignora otros archivos; Colombia solo *.md/.env*/.gitignore/panel.html); todo api/*.js se sirve como función serverless -> alcanzables en panama.playablancaresidences.com/api/conversion y landing-colombia-full.vercel.app/api/conversion. (2) SIN AUTENTICACIÓN: los únicos filtros son CORS, method==POST, existencia de user_data y allowlist de event_name. No hay clave/HMAC/firma/rate-limit ni chequeo Origin/Referer server-side. (3) El CORS NO protege (correcto): un POST con curl ignora Access-Control-Allow-Origin. (4) HubSpot batch/upsert con idProperty:'email' (Panamá L74-77, Colombia L80-82) CREA el contacto si el email no existe -> creación/contaminación de contactos con email arbitrario. (5) ALLOWED_EVENTS incluye 'Lead' y 'Purchase' (Panamá L29, Colombia L36) -> inyección de eventos falsos a pixels 2195.../1923... POR QUÉ MEDIA Y NO ALTA: es un vector de integridad/abuso, NO de confidencialidad: no expone ningún secreto/PII (la respuesta solo refleja el resultado de Meta CAPI), no hay exfiltración, ni toma de cuenta, ni movimiento de dinero. El write a HubSpot es limitado: savePassport solo corre si el payload trae fbc/fbp/event_id y solo puede escribir fb_fbc/fb_fbp/fb_event_id (más crear contactos basura); no sobrescribe nombre/teléfono ni campos de negocio existentes. Además el endpoint DEBE aceptar llamadas anónimas del navegador por diseño (PageView de cualquier visitante), por lo que es un patrón de riesgo aceptado común; el daño real (envenenar optimización de campañas o inflar contactos en HubSpot) exige un atacante motivado y volumen sostenido. Fix recomendado (coincide con el finder): chequeo de Origin/Referer server-side + rate limiting por IP + validación del payload antes del upsert. Relevante para el negocio por el KPI de calidad de lead y por el cobro por tramos de contactos de HubSpot (hubo crisis de facturación previa).

## [16] `MEDIA` — PII real de 3 leads hardcodeada en HTML público (SAMPLE_DATA) — legible sin clave ni API

- **Archivo:** web-panama-LIVE/crmdataplayablanca.html:453-458
- **Público:** True
- **Evidencia:** SAMPLE_DATA=[ {"nombre":"MARTA BONILLA","tel":"+50769429691","email":"mbg192839@gmail.com",..."estado":"","presupuesto":"$195mil - $300mil usd","asesor":"Tifany Pinzon"}, {"nombre":"Marcelino Ríos","tel":"+50762197654","email":"marcelinoriosabrego95@gmail.com","estado":"no_interesado",...}, {"nombre":"Benja","tel":"+50767089124","email":"ruth12r09@gmail.com","estado":"no_contactable",...} ]
- **Riesgo:** view-source de crmdataplayablanca.html expone nombre completo, teléfono +507 real, email real, presupuesto y estado (incl. no_interesado/no_contactable) de 3 personas reales SIN necesidad de clave ni de llamar al API. Fuga directa de datos personales que SOBREVIVE a la rotación de la clave (finding #1). Riesgo de incumplimiento de protección de datos (habeas data CO / PA).
- **Fix:** Reemplazar SAMPLE_DATA por datos 100% ficticios (o vaciarlo) y redeploy. Nunca usar registros reales como fallback embebido. Revisar backups/versiones donde también quedó (ceoapp1409.bak, crmdataplayablanca previo).
- **Verificación:** CONFIRMADO real. Archivo /Users/juanescorcha/Downloads/PROYECTOS IA/META ADS/web-panama-LIVE/crmdataplayablanca.html líneas 453-458: SAMPLE_DATA es un const JS inline dentro de <script>, servido en el HTML estático. El archivo NO está en .vercelignore (que SÍ bloquea dashboard-leads.html, ceoapp1409.bak y crm_v2.html "con PII") -> es público en panama.playablancaresidences.com/crmdataplayablanca. Cualquiera con view-source o curl lee la PII sin clave ni llamar a /api/crm; el gate JS y la KEY son irrelevantes porque el array va horneado en el documento. Datos reales: 3 registros con hsid de HubSpot, emails personales reales (mbg192839@gmail.com, marcelinoriosabrego95@gmail.com, ruth12r09@gmail.com — nótese "Benja" con email ruth12r09, típico de data real desordenada), teléfonos +507 reales, presupuesto y estado (no_interesado/no_contactable). El 4º registro (Ana Gomez / +573001234567 / ana@gmail.com) es placeholder ficticio evidente, así que el conteo "3 leads reales" del finding es correcto. Es una fuga independiente que SOBREVIVE a la rotación de la clave del finding #1. CORRIJO severidad de critica -> media: es real y hay que arreglarlo (vaciar/ficticiar SAMPLE_DATA y redeploy, y revisar backups), pero el alcance es 3 registros hardcodeados, no toda la base; el tier crítico corresponde al finding #1 (clave maestra que abre /api/crm sobre miles de leads).

## [17] `MEDIA` — Endpoints CAPI (conversion.js) sin autenticación ni rate limiting → inyección de contactos en HubSpot y envenenamiento del pixel

- **Archivo:** web-panama-LIVE/api/conversion.js:17-97 · landing-colombia-full/api/conversion.js:23-102
- **Público:** True
- **Evidencia:** No hay chequeo de clave; savePassport() hace fetch a /crm/v3/objects/contacts/batch/upsert con idProperty:'email' → crea/actualiza contactos. El header Access-Control-Allow-Origin restringe navegadores, NO peticiones servidor-a-servidor.
- **Riesgo:** Ambos endpoints CAPI aceptan POST anónimos sin límite de tasa. El CORS no protege (un atacante hace POST directo con curl, saltándose el navegador). Consecuencias: (1) envenenar el pixel de Meta con miles de eventos Lead/Purchase falsos (arruina optimización y métricas); (2) vía savePassport, upsert por email crea/sobrescribe contactos arbitrarios en HubSpot (contaminación del CRM, sobrescritura de fb_fbc/fbp/event_id de contactos reales). Sin rate limit, también sirve para agotar cuota/costos.
- **Fix:** Añadir rate limiting (p.ej. Upstash/@vercel/kv o middleware) por IP; validar un token efímero/firma emitido por la landing o un desafío tipo Turnstile/hCaptcha antes de aceptar el evento; no crear contactos nuevos desde este endpoint (usar update-only o whitelisting de emails ya existentes); validar/limitar custom_data.
- **Verificación:** REAL y explotable sin credenciales. Verificado: ambos api/conversion.js se sirven públicamente (no están en .vercelignore; api/ no excluido) y las landings los llaman por fetch desde el navegador. NO hay auth/clave/rate-limit; los únicos filtros son método POST, user_data presente y event_name en whitelist (que incluye Lead y Purchase). El CORS Access-Control-Allow-Origin solo se pone en la RESPUESTA; el handler nunca rechaza por Origin, así que un POST con curl/servidor-a-servidor lo procesa igual (finder correcto). Vectores confirmados: (1) envenenar pixel Meta con eventos Lead/Purchase falsos (custom_data pasa sin validar); (2) savePassport hace upsert HubSpot idProperty:email → crea contactos arbitrarios y sobrescribe fb_fbc/fb_fbp/fb_event_id de contactos reales. AJUSTE de severidad alta→media: (a) NINGÚN secreto se expone ni exfiltra (META_ACCESS_TOKEN y HUBSPOT_TOKEN quedan server-side en process.env; el branch ?debug solo devuelve la respuesta de HubSpot, no el token); (b) es un vector de integridad/abuso solo-escritura, no de confidencialidad; (c) la escritura en HubSpot está limitada a 3 campos fb_* + creación de contacto vacío (no toca nombre/teléfono, no lee, no borra); (d) el acceso anónimo es en parte inherente a un endpoint CAPI/tracking público (el pixel de navegador ya permite disparar eventos). Vale la pena arreglar (rate-limit por IP + validar Origin/token efímero + update-only en HubSpot + validar custom_data), pero está por debajo del hallazgo crítico #1 (clave maestra que da lectura de TODOS los leads).

## [18] `BAJA` — crmceo.html: el gate es correcto, pero la clave que lo abre es la maestra filtrada

- **Archivo:** web-panama-LIVE/crmceo.html:285 (gate) · :585 tryKey → /api/panel
- **Público:** True
- **Evidencia:** line 572: KEY desde ?k= o sessionStorage (NO horneada). line 585: fetch(`/api/panel?key=...`) valida server-side; si falla → showGate('Clave incorrecta'). Es el patrón correcto a copiar. panel.js:105 acepta RALPH_KEY/ARIE_KEY/CRM_KEY/DASH_KEY.
- **Riesgo:** El página en sí sí protege (no revela data sin clave válida). Pero como /api/panel también acepta la CRM_KEY/DASH_KEY maestra —que está filtrada en las otras dos páginas— cualquiera puede teclear esa clave aquí y entrar como 'Juan'. Queda comprometido por el mismo root cause, no por un fallo propio.
- **Fix:** Al rotar la clave maestra y sacarla del front, crmceo queda seguro. Opcional: que /api/panel deje de aceptar la CRM_KEY/DASH_KEY para el panel humano y sólo acepte RALPH_KEY/ARIE_KEY.
- **Verificación:** Confirmado el hecho, pero severidad ajustada de media→baja (el finder lo exageró como hallazgo independiente). VERIFICADO: (1) web-panama-LIVE/crmceo.html es público (NO está en .vercelignore). (2) Su gate es CORRECTO y sin fallo propio: crmceo.html:572 lee KEY de ?k=/sessionStorage (no horneada) y :585 tryKey() valida server-side vía /api/panel, con showGate('Clave incorrecta') en 401 — no revela data ni filtra clave alguna; es el patrón correcto. (3) api/panel.js:105 okKeys=[RALPH_KEY,ARIE_KEY,CRM_KEY,DASH_KEY] y :109 mapea CRM_KEY/DASH_KEY→'Juan'. (4) Cadena root-cause confirmada: ceoapp1409.html:488 (también público) hornea const KEY='890D65CDA777439C932F' y la usa (:1095) contra /api/crm; crm.js:94 valida contra process.env.CRM_KEY||DASH_KEY → ese literal ES la CRM_KEY/DASH_KEY. Como panel.js también acepta esas llaves, la misma clave pública abre /api/panel (directo o por el gate) como 'Juan'. CONCLUSIÓN: la data SÍ es alcanzable por un atacante sin credenciales previas (la clave está en fuente pública), así que real=true. PERO como hallazgo propio es baja: crmceo no tiene defecto (gate correcto), queda 100% subsumido por el crítico #1 (clave maestra filtrada), no agrega superficie nueva (el atacante puede pegarle directo a /api/panel/crm/leads/reporte sin pasar por crmceo) y panel.js:4 devuelve data agregada sin PII cruda ni tokens (menos sensible que /api/crm ya expuesto). Remediación = la misma de #1: rotar la clave y sacarla de ceoapp1409.html; opcional endurecer /api/panel para que NO acepte CRM_KEY/DASH_KEY y solo RALPH_KEY/ARIE_KEY. No es un vector separado que sume al riesgo global; es una manifestación del root cause.

## [19] `BAJA` — conversion.js: relay CAPI POST sin clave (Panamá y Colombia)

- **Archivo:** web-panama-LIVE/api/conversion.js:23 · landing-colombia-full/api/conversion.js
- **Público:** True
- **Evidencia:** conversion.js:18 CORS al dominio propio, :23 exige POST, :29-30 ALLOWED_EVENTS whitelist, sin validación de clave. :66 hace lookup a HubSpot por email para enriquecer el evento (server-side, no lo devuelve al cliente).
- **Riesgo:** Endpoint abierto por diseño (el pixel del navegador lo necesita). Riesgo bajo: no expone data almacenada (el resultado del lookup de HubSpot no se retorna al caller). Abusable para inyectar eventos falsos al pixel/CAPI o como oráculo de existencia de email si se afinara. No es una fuga de datos.
- **Fix:** Aceptable dejarlo. Endurecer opcional: rate-limit, verificar Origin/Referer estrictamente y no ejecutar el lookup de HubSpot para orígenes no confiables. Prioridad baja frente a la clave maestra.
- **Verificación:** CONFIRMADO real y alcanzable sin credenciales. Ambos web-panama-LIVE/api/conversion.js y landing-colombia-full/api/conversion.js se sirven públicos (no cubiertos por .vercelignore; el grep 'conversion' solo matcheo el SOP docx/pdf, no el api/*.js). Endpoint POST sin clave: solo whitelist ALLOWED_EVENTS + header CORS (que no bloquea curl server-to-server). CORRECCION AL FINDER: la interaccion con HubSpot (savePassport, lineas ~65-80) NO es un 'lookup/read que no se devuelve' sino un batch/upsert (ESCRITURA) con idProperty:email → un atacante sin credenciales puede CREAR/MODIFICAR contactos del CRM (enviando email + fbc/fbp/event_id) y envenenar los campos fb_fbc/fb_fbp/fb_event_id de contactos existentes, ademas de inyectar eventos falsos a CAPI/pixel. Matiz extra SOLO Panama: linea 97 con ?debug=1 devuelve el cuerpo del upsert de HubSpot (_hs) → oraculo debil de existencia de email + HubSpot id (Colombia no retorna el resultado HS). SEVERIDAD SIGUE BAJA: la escritura esta acotada a 3 campos de atribucion keyed por email; no permite props arbitrarias, no lee la base de leads, no expone tokens ni la clave maestra. Es abuso/pollution + oraculo debil, no una fuga de datos almacenados. El finder acerto la severidad pero equivoco la direccion (es escritura/upsert, no read; y omitio el leak via ?debug en Panama). Fix opcional sigue de baja prioridad frente al hallazgo critico de la clave maestra.

## [20] `BAJA` — Sin rate limiting ni throttling en ningún endpoint /api

- **Archivo:** web-panama-LIVE/api/* y landing-colombia-full/api/*
- **Público:** True
- **Evidencia:** grep de rate.?limit/throttle/429 en las carpetas api solo halla el backoff interno hacia HubSpot; no hay limitación de peticiones entrantes por IP/clave.
- **Riesgo:** Permite: fuerza bruta de claves, abuso masivo del endpoint sin auth /api/conversion (envenenar Pixel/HubSpot), agotamiento de recursos y cuotas (parte.js→Gemini, panel.js→Meta), y riesgo de baneo del número de WhatsApp por volumen (wa-grupo/hs-webhook).
- **Fix:** Añadir rate limiting por IP y por clave (p.ej. Vercel Edge Middleware o Upstash Ratelimit) especialmente en /api/conversion, /api/wa-grupo, /api/hs-webhook y los endpoints de datos.
- **Verificación:** CONFIRMADO que no hay rate limiting entrante en ningún endpoint /api de ambos deploys (los únicos matches 429/rate-limit son backoff INTERNO hacia HubSpot en crm.js:131-136 y leads.js:39; no hay middleware.* ni config de firewall en vercel.json). Los endpoints son públicos. Sin embargo, el finder EXAGERÓ (media→baja): de los 4 vectores citados, 3 no se sostienen. (1) 'Fuerza bruta de claves' = inviable: claves de ~80 bits (20 hex), no las protege el rate limit sino la entropía, y además la clave ya está expuesta en HTML público (hallazgo #1), así que es moot. (3) 'Cuotas parte.js/panel.js' = gateados por CRM_KEY/PANEL_KEY (parte.js:19, panel.js:107). (4) 'Baneo WhatsApp wa-grupo/hs-webhook' = gateados por clave (wa-grupo.js:24, hs-webhook.js:178; escrituras CRM exigen HS_CONTROL_KEY). El ÚNICO vector genuinamente sin credenciales es (2): conversion.js (PA+CO) NO tiene clave (solo CORS por header Origin, evadible con curl server-side) → floodeable para contaminar el Pixel de Meta y hacer upserts basura en HubSpot (limitado a 3 props por email). Su causa raíz real es la falta de auth en conversion.js, no la ausencia de rate limit; y Vercel mitiga parcialmente el DoS a nivel plataforma (auto-scaling), dejando como residual costo de invocaciones + polución de datos. Es real como brecha de hardening/defensa-en-profundidad, pero severidad BAJA, no media.
